name: Build & Test Audiveris

on:
  - push

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TESSDATA_PREFIX: /home/runner/work/audiveris/audiveris/tessdata
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Install Tesseract language files
        uses: actions/install-tessdata@v1
        with:
          language: eng
      - name: Build & Test Audiveris
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: build